spring.application.name=mutualfundcalc

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server.port=${PORT:8080}

openai.api.key=${OPENAI_API_KEY}
openai.model=${OPENAI_MODEL:gpt-5-nano}